---
title: "imdb_analyses"
author: "Justin Verhulst"
date: "2023-01-20"
output: html_document
---
#Inladen libraries, environment opschonen, importeren opgeschoonde dataset
```{r}
#Opschonen environment
rm(list = ls()) 

#Ophalen libraries en opgeschoonde last.fm dataset
libraries <- readRDS("libraries.rds")
lapply(libraries, require, character.only = TRUE)
imdb <- readRDS("imdb.rds")

#Mogelijke aanvullende analyses:
# - Een tabel met laatst bekeken films
# - Op welke dag van de week kijk ik het vaakste films?
# - Film Genre word cloud
```

#Plot - Aantal films gezien per releasejaar
```{r}
p_films_jaar <- imdb %>%
  
  #maak een selectie per jaar
  group_by(year) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  
  #maak plot
  ggplot(aes(x = year, y = count)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black",fill = "#ad42f5") +
  #geom_text(aes(label=count), vjust=0.3, hjust = -0.1) + #eventueel cijfers bij de bars

  #Geef labels mee 
  labs(x = "", y = "", title = "Aantal films bekeken per releasejaar") +
 
  #Voeg thema toe en maak wat aanpassingen
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = c(0.9, 0.5),legend.title = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.ticks.x = element_blank(),axis.ticks.y = element_blank(), axis.text = element_text(face="bold")) + 
  
  #X en Y as netter maken
  scale_y_continuous(expand = c(0, 0),limits = c(0, 55), breaks = seq(0, 55, by = 5)) +
  scale_x_continuous(limits = c(1910, 2024), breaks = seq(1910, 2023, by = 10))

```

#Plot - Aantal films gekeken per jaar
```{r}
#prep data:
x <- imdb %>%
  mutate(jaar_bekeken = year(date_rated))%>% 
  #maak een selectie per jaar
  group_by(title_type, jaar_bekeken) %>% 
  summarise(count = n(), jaar_bekeken) %>% 
  arrange(desc(count))%>%
  mutate(count = 1)

#maak de plot:
p_jaar2 <- ggplot(x, aes(fill=title_type, y=count, x=jaar_bekeken)) + 
    geom_bar(position="stack", stat="identity") +
  labs(x = "", y = "", title = "Aantal films of series bekeken per jaar") +
  theme_bw() +
  
  theme(plot.title = element_text(hjust = 0.5), legend.title = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.ticks.x = element_blank(),axis.ticks.y = element_blank(), axis.text = element_text(face="bold"))+
  
  scale_y_continuous(expand = c(0, 0),limits = c(0, 120), breaks = seq(0, 120, by = 10)) +
  scale_x_continuous(limits = c(2007, 2024), breaks = seq(2007, 2023, by = 2)) +
  scale_fill_discrete(labels=c('Films', 'Series'))


```

#Plot - Ratings
```{r}
p_ratings <- imdb %>%
  
  #maak een selectie per jaar
  group_by(your_rating) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  
  #maak plot
  ggplot(aes(x = your_rating, y = count)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black",fill = "#ad42f5") +
  #geom_text(aes(label=count), vjust=0.3, hjust = -0.1) + #eventueel cijfers bij de bars

  #Geef labels mee 
  labs(x = "", y = "Minuten", title = "Cijfers gegeven aan films en series") +
 
  #Voeg thema toe en maak wat aanpassingen
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = c(0.9, 0.5),legend.title = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.ticks.x = element_blank(),axis.ticks.y = element_blank(), axis.text = element_text(face="bold")) + 
  
  #X en Y as netter maken
  scale_y_continuous(expand = c(0, 0),limits = c(0, 350), breaks = seq(0, 350, by = 25)) +
  scale_x_continuous(expand = c(0, 0),limits = c(0, 11), breaks = seq(1, 10, by = 1)) 

```

#Plot - cumulatief over de jaren heen
```{r}
p_cumulatief <- imdb %>%
  arrange(date_rated)%>%
  mutate(cumulatief = 1)%>%
  mutate(cumulatief = cumsum(cumulatief))%>%
  
  #maak plot
  ggplot(aes(x = date_rated, y = cumulatief)) + 
  geom_line() +

  #Geef labels mee 
  labs(x = "", y = "", title = "Aantal films en series gezien over de jaren heen") +
 
  #Voeg thema toe en maak wat aanpassingen
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = c(0.9, 0.5),legend.title = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.ticks.x = element_blank(),axis.ticks.y = element_blank(), axis.text = element_text(face="bold"))+
  
  #X en Y as netter maken
 scale_y_continuous(expand = c(0, 0),limits = c(0, 800), breaks = seq(0, 800, by = 100)) #+
#scale_x_date(date_breaks = "years" , date_labels = "'%y", breaks = date_breaks("years"))

```

#Plot - tijdsduur films
```{r}
p_tijdsduur <- imdb %>%
  
  #Alleen films selecteren
  filter(title_type == "movie") %>%
  #Maak categorieën voor tijdsduur
  mutate(tijdsduur_categorie = ifelse(runtime_mins < 80, "< 80 min", NA),
         tijdsduur_categorie = ifelse(runtime_mins >= 80 & runtime_mins < 100, "80 - 100 min", tijdsduur_categorie),
         tijdsduur_categorie = ifelse(runtime_mins >= 100 & runtime_mins < 120, "100 - 120 min", tijdsduur_categorie),
         tijdsduur_categorie = ifelse(runtime_mins >= 120 & runtime_mins < 140, "120 - 140 min", tijdsduur_categorie),
         tijdsduur_categorie = ifelse(runtime_mins >= 140 & runtime_mins < 160, "140 - 160 min", tijdsduur_categorie),
         tijdsduur_categorie = ifelse(runtime_mins >= 160 & runtime_mins < 180, "160 - 180 min", tijdsduur_categorie),
         tijdsduur_categorie = ifelse(runtime_mins > 180, "> 180 min", tijdsduur_categorie) 
         )%>%
  
  #maak een selectie per jaar
  group_by(tijdsduur_categorie) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  
  #maak plot
  ggplot(aes(x = tijdsduur_categorie, y = count)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black",fill = "#ad42f5") +
  #geom_text(aes(label=count), vjust=0.3, hjust = -0.1) + #eventueel cijfers bij de bars

  #Geef labels mee 
  labs(x = "", y = "", title = "Aantal films gezien van een bepaalde tijdsduur") +
 
  #Voeg thema toe en maak wat aanpassingen
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = c(0.9, 0.5),legend.title = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.ticks.x = element_blank(),axis.ticks.y = element_blank(), axis.text = element_text(face="bold")) + 
  
  #X en Y as netter maken
  scale_y_continuous(expand = c(0, 0),limits = c(0, 300), breaks = seq(0, 300, by = 25)) +
  scale_x_discrete(limits = c("< 80 min", "80 - 100 min", "100 - 120 min", "120 - 140 min", "140 - 160 min", "160 - 180 min", "> 180 min"))
  
```

#Plot - Populairste regisseurs
```{r} 
p_regisseurs <- imdb %>%
  
  #pak de eerste regisseur als er meerdere zijn (je pakt de string voor de komma)
  mutate(regisseur = gsub(",.*$", "", directors)) %>% 
  filter(regisseur != "")%>% 
  
  #maak een selectie per jaar
  group_by(regisseur) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>%
  top_n(10) %>%
  
  #maak plot
  ggplot(aes(x = reorder(regisseur, count), y = count)) + 
  geom_bar(stat = "identity", position = "dodge", color = "black",fill = "#ad42f5") +
  geom_text(aes(label=count), vjust=0.3, hjust = -0.4) + 
  
  #Het moet een horizontale barchart zijn
  coord_flip() +

  #Geef labels mee 
  labs(x = "", y = "", title = "Aantal films gezien per regisseur") +
 
  #Voeg thema toe en maak wat aanpassingen
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5), legend.position = c(0.9, 0.5),legend.title = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.ticks.x = element_blank(),axis.ticks.y = element_blank(), axis.text = element_text(face="bold")) +
 scale_y_continuous(expand = c(0, 0), limits = c(0, 16), breaks = seq(0, 16, by = 2))
```

#Figuren exporteren
```{r}

#Exporteren met meerdere visuals in 1 overzicht 
plot.list <- list(p_cumulatief,
                  p_films_jaar,
                  p_jaar2,
                  p_regisseurs
                  )
layout_mat<-rbind(c(1,2),
                  c(3,4)
                  )

plots<-marrangeGrob(plot.list, layout_matrix=layout_mat)
ggsave( filename="plots_films_small.pdf", plots, width=29.7, height=21, units="cm")

#Exporteren 1 visual per pagina
pdf("plots_films_large.pdf")

p_cumulatief
p_films_jaar
p_jaar2
p_regisseurs

dev.off()

```